# Generated by Django 4.2 on 2026-02-15 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('job_id', models.IntegerField()),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SkillUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('skill_name', models.CharField(max_length=255)),
                ('usage_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('activity_type', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
