# Generated by Django 4.2 on 2026-08-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planning', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectevidence',
            name='verification_status',
            field=models.CharField(choices=[('self_reported', 'Self-Reported'), ('ai_assessed', 'AI-Assessed'), ('organization_verified', 'Organization-Verified')], default='self_reported', max_length=30),
        ),
    ]
