# Generated by Django 4.2 on 2026-08-19 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0002_alter_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='problem',
            name='expected_outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_real_world',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='original_description',
            field=models.TextField(blank=True, help_text='Preserved raw submitted problem statement'),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='problem',
            name='source_type',
            field=models.CharField(choices=[('REAL_WORLD_ORGANIZATION', 'Real-World Organization'), ('COMPANY', 'Private Company'), ('STARTUP', 'Startup'), ('HOSPITAL', 'Hospital / Healthcare'), ('NGO', 'NGO / Non-Profit'), ('GOVERNMENT_PUBLIC', 'Government / Public Body'), ('COMMUNITY', 'Community Body'), ('STUDENT_SUBMITTED', 'Student Submitted'), ('AI_GENERATED_PRACTICE', 'AI-Generated Practice Project')], default='COMPANY', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='match_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='match_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('available', 'Available Opportunity'), ('selected', 'Selected by Student'), ('in_progress', 'In Progress'), ('submitted', 'Submitted for Technical Evaluation'), ('under_evaluation', 'Under Technical Evaluation'), ('revision_required', 'Revision Required'), ('resubmitted', 'Resubmitted for Review'), ('owner_review', 'Pending Problem Owner Review'), ('accepted', 'Accepted by Problem Owner'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='in_progress', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectevidence',
            name='evidence_statement',
            field=models.TextField(help_text='Formal verified statement'),
        ),
        migrations.CreateModel(
            name='ProjectSubmissionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1)),
                ('github_url', models.URLField(max_length=500)),
                ('published_url', models.URLField(help_text='Live published application/API URL', max_length=500)),
                ('documentation', models.TextField(help_text='Project architecture and setup docs')),
                ('requirement_mapping', models.JSONField(default=list, help_text='Maps Requirement ID -> Implemented Feature -> Evidence')),
                ('demo_video_url', models.URLField(blank=True, max_length=500)),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('deployment_status', models.CharField(choices=[('reachable', 'Reachable (HTTP 200/Success)'), ('unreachable', 'Unreachable'), ('checking', 'Checking Reachability'), ('deployment_issue', 'Deployment Issue')], default='checking', max_length=30)),
                ('deployment_check_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('project', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ProjectOwnerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('ACCEPT', 'Accept Real-World Project'), ('REQUEST_CHANGES', 'Request Changes'), ('REJECT', 'Reject Project')], default='ACCEPT', max_length=30)),
                ('comments', models.TextField(help_text='Mandatory comments for Request Changes or Reject')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_owner_reviews', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_reviews', to='problems.project')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_reviews', to='problems.projectsubmissionversion')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_evaluations', models.JSONField(default=list, help_text='Per-requirement eval: status, reason, missing_component, suggested_action')),
                ('automated_checks', models.JSONField(default=dict, help_text='Build, GitHub, Live URL reachability, mapping completeness')),
                ('requirement_coverage_pct', models.FloatField(default=0.0)),
                ('critical_requirement_coverage_pct', models.FloatField(default=0.0)),
                ('functional_requirement_coverage_pct', models.FloatField(default=0.0)),
                ('is_ready_for_owner_review', models.BooleanField(default=False, help_text='False if Critical requirement coverage < 100%')),
                ('quality_score', models.IntegerField(default=0)),
                ('quality_breakdown', models.JSONField(blank=True, default=dict)),
                ('evaluator_decision', models.CharField(choices=[('ACCEPT', 'Accept & Send to Owner'), ('REVISION_REQUIRED', 'Revision Required'), ('REJECT', 'Reject Submission'), ('REQUEST_MORE_INFO', 'Request More Information')], default='REVISION_REQUIRED', max_length=30)),
                ('evaluator_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_evaluations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='problems.project')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='problems.projectsubmissionversion')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.CharField(help_text='e.g. REQ-001', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('req_type', models.CharField(choices=[('functional', 'Functional Requirement'), ('non_functional', 'Non-Functional Requirement'), ('technical', 'Technical / System Requirement')], default='functional', max_length=30)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='CRITICAL', max_length=20)),
                ('source', models.CharField(choices=[('OWNER_DEFINED', 'Owner Defined'), ('AI_INFERRED', 'AI Inferred')], default='OWNER_DEFINED', max_length=30)),
                ('status', models.CharField(choices=[('pending_owner_confirmation', 'Pending Owner Confirmation'), ('confirmed', 'Confirmed Official Requirement'), ('rejected', 'Rejected by Owner')], default='confirmed', max_length=35)),
                ('acceptance_criteria', models.TextField()),
                ('verification_method', models.CharField(choices=[('functional_test', 'Functional Test'), ('code_review', 'Code Review'), ('live_url_check', 'Live Published URL Check'), ('doc_review', 'Documentation Review')], default='functional_test', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='problems.problem')),
            ],
            options={
                'ordering': ['requirement_id'],
                'unique_together': {('problem', 'requirement_id')},
            },
        ),
    ]
