# Generated by Django 4.2 on 2026-02-18 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry'), ('mid', 'Mid'), ('senior', 'Senior')], default='entry', max_length=20)),
                ('interview_type', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], default='moderate', max_length=20)),
                ('question_count', models.IntegerField(default=5)),
                ('total_score', models.FloatField(default=0.0)),
                ('technical_accuracy', models.FloatField(default=0.0)),
                ('communication_score', models.FloatField(default=0.0)),
                ('depth_of_knowledge', models.FloatField(default=0.0)),
                ('clarity_score', models.FloatField(default=0.0)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('improvement_areas', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockInterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('weaknesses', models.TextField(blank=True, null=True)),
                ('improved_answer', models.TextField(blank=True, null=True)),
                ('missed_concepts', models.JSONField(default=list)),
                ('technical_accuracy', models.FloatField(default=0.0)),
                ('communication_rating', models.FloatField(default=0.0)),
                ('order', models.IntegerField(default=0)),
                ('is_answered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.mockinterview')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
