# Generated by Django 4.2 on 2026-02-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterview',
            name='communication_readiness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='confidence_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='instant_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='interview_mode',
            field=models.CharField(choices=[('standard', 'Standard'), ('rapid_fire', 'Rapid Fire'), ('deep_dive', 'Deep Dive'), ('hr_simulation', 'HR Simulation'), ('technical_panel', 'Technical Panel')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='performance_trend',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='technical_readiness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mockinterviewquestion',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='mockinterviewquestion',
            name='completeness_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mockinterviewquestion',
            name='depth_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mockinterviewquestion',
            name='difficulty_badge',
            field=models.CharField(default='Moderate', max_length=50),
        ),
        migrations.AddField(
            model_name='mockinterviewquestion',
            name='is_follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mockinterviewquestion',
            name='relevance_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mockinterviewquestion',
            name='reviewer_intent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewquestion',
            name='sample_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewquestion',
            name='structure_score',
            field=models.FloatField(default=0.0),
        ),
    ]
