# Generated by Django 4.2 on 2026-02-22 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviews', '0002_mockinterview_communication_readiness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterview',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='eye_contact_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='filler_words_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='nervousness_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='speaking_pace',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewquestion',
            name='audio_answer_url',
            field=models.FileField(blank=True, null=True, upload_to='interviews/audio/'),
        ),
        migrations.AddField(
            model_name='mockinterviewquestion',
            name='avg_pitch',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mockinterviewquestion',
            name='behavioral_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewquestion',
            name='clarity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mockinterviewquestion',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mockinterviewquestion',
            name='filler_words',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='LiveInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100, unique=True)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hiring_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_sessions', to=settings.AUTH_USER_MODEL)),
                ('mock_interview', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviews.mockinterview')),
            ],
        ),
    ]
