# Generated by Django 4.2 on 2026-02-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartalert',
            name='ai_reasoning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartalert',
            name='behavioral_flag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smartalert',
            name='confidence_score',
            field=models.IntegerField(default=0, help_text='AI confidence in this insight'),
        ),
        migrations.AddField(
            model_name='smartalert',
            name='data_reference_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='smartalert',
            name='impact_score',
            field=models.IntegerField(default=0, help_text='0-100 impact on career readiness'),
        ),
        migrations.AddField(
            model_name='smartalert',
            name='improvement_projection',
            field=models.IntegerField(default=0, help_text='Projected score increase if actioned'),
        ),
        migrations.AddField(
            model_name='smartalert',
            name='predicted_risk_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smartalert',
            name='secondary_action_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='smartalert',
            name='secondary_action_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='smartalert',
            name='alert_type',
            field=models.CharField(choices=[('skill_gap', 'Skill Gap'), ('roadmap', 'Roadmap Progress'), ('interview', 'Interview Performance'), ('readiness', 'Job Readiness'), ('market', 'Market Trend'), ('predictive_risk', 'Predictive Risk'), ('opportunity', 'Growth Opportunity'), ('behavioral', 'Behavioral Insight'), ('regression', 'Performance Regression'), ('achievement', 'Achievement Milestone')], max_length=50),
        ),
    ]
