# Generated by Django 4.2 on 2026-02-18 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_current_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_readiness_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='market_readiness_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Rising', 'Rising'), ('Competitive', 'Competitive'), ('Expert', 'Expert')], default='Beginner', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_completeness',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('resume', 'Resume Analyzed'), ('roadmap', 'Roadmap Updated'), ('skill', 'Skill Added'), ('interview', 'Interview Practice'), ('chat', 'AI Chat'), ('login', 'Logged In')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('impact_score', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Tools', 'Tools'), ('Soft Skills', 'Soft Skills'), ('Other', 'Other')], default='Other', max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
    ]
