# Generated by Django 4.2 on 2026-02-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_two_factor_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_visibility',
            field=models.BooleanField(default=True),
        ),
    ]
