# Generated by Django 4.2 on 2026-08-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='branch_domain',
            field=models.CharField(blank=True, default='Computer Science / IT', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='career_interests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_year_semester',
            field=models.CharField(blank=True, default='3rd Year', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(blank=True, default='B.Tech', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='software_tools',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
