# Generated by Django 4.2 on 2026-08-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_branch_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('problem_owner', 'Problem Owner / Requester'), ('evaluator', 'Project Evaluator'), ('admin', 'Platform Super Admin')], default='student', max_length=30),
        ),
    ]
