# Generated by Django 4.2 on 2026-02-17 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0002_seed_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255)),
                ('skill_name', models.CharField(max_length=100)),
                ('importance_level', models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical'), (5, 'Mandatory')], default=3)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skill'), ('tools', 'Tools')], default='technical', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seniority', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior')], default='junior', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('required_skills', models.JSONField(blank=True, default=dict, help_text="Mapping of skill names to required level/weight, e.g. {'Python': {'weight': 3, 'level': 'intermediate'}}")),
            ],
        ),
        migrations.AlterField(
            model_name='userskill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skill'), ('tools', 'Tools'), ('programming', 'Programming'), ('data', 'Data'), ('design', 'Design'), ('devops', 'DevOps'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text='Skill level 1-5'),
        ),
        migrations.CreateModel(
            name='SkillGapReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('readiness_score', models.FloatField(default=0.0)),
                ('technical_score', models.FloatField(default=0.0)),
                ('soft_skill_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerReadinessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readiness_score', models.PositiveIntegerField(help_text='0-100 readiness score')),
                ('skill_gaps', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='skills.roletemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
