# Generated by Django 4.2 on 2026-02-17 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255, unique=True)),
                ('total_open_jobs', models.PositiveIntegerField(default=0)),
                ('top_companies', models.JSONField(default=list, help_text='List of top hiring companies')),
                ('avg_salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('avg_salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remote_ratio', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of remote jobs (0.00 to 100.00)', max_digits=5)),
                ('onsite_ratio', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of onsite jobs (0.00 to 100.00)', max_digits=5)),
                ('location_heatmap', models.JSONField(default=dict, help_text='Mapping of location to job count')),
                ('top_required_skills', models.JSONField(default=list, help_text='List of top required skills with counts')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserJobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(decimal_places=2, help_text='Match percentage (0-100)', max_digits=5)),
                ('missing_skills', models.JSONField(default=list, help_text='List of skills user is missing for this role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_matches', to='jobs.jobdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job_data')},
            },
        ),
    ]
