# Generated by Django 4.2 on 2026-02-15 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroadmap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roadmaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='roadmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='roadmaps.roadmap'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='related_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmaps', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='roadmap_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to='roadmaps.roadmapstep'),
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_trackers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='progresstracker',
            unique_together={('user', 'roadmap_step')},
        ),
    ]
