# Generated by Django 6.0.2 on 2026-02-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0003_youtubevideo_uservideoprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='required_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='skills_list',
            field=models.JSONField(default=list),
        ),
    ]
