# Generated by Django 6.0.2 on 2026-02-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0004_roadmap_required_skills_roadmapstep_skills_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapstep',
            name='duration_weeks',
            field=models.IntegerField(default=2, help_text='Estimated weeks to complete this phase'),
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='estimated_hours',
            field=models.IntegerField(default=20, help_text='Estimated total hours for this phase'),
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='recommended_resources',
            field=models.JSONField(default=list, help_text='List of courses, tutorials, books'),
        ),
    ]
