# Generated by Django 4.2 on 2026-02-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0005_roadmapstep_duration_weeks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideoprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
