# Generated by Django 4.2 on 2026-02-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0006_uservideoprogress_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresstracker',
            name='confidence_index',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='mastery_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='mini_mock_results',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='outcome_projection',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='time_spent_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='skill_demand',
            field=models.JSONField(default=dict, help_text='Demand level per skill in this step'),
        ),
        migrations.AddField(
            model_name='uservideoprogress',
            name='ai_extraction',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='uservideoprogress',
            name='drop_off_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uservideoprogress',
            name='focus_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='uservideoprogress',
            name='impact_level',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='uservideoprogress',
            name='linked_skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uservideoprogress',
            name='rewatch_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uservideoprogress',
            name='watch_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
